### ISSUE TITLE
feat: release signed win installer for sltt-app with auto-updates

### ISSUE THREAD

**Issue by ericpyle** [ubsicap/sltt-app#1]

**Comment by ericpyle** [comment]
Allison,
1) To test auto-updater:

1. Install previous release: https://github.com/ubsicap/sltt-app/releases/download/v1.0.15/sltt-app-Setup-1.0.15.exe
2. Install latest release https://github.com/ubsicap/sltt-app/releases/latest/download/sltt-app-Setup-1.0.16.exe
3. Wait until you see a notification that says a new update has been downloaded. 
4. Close and restart app

2) To test offline:
2.1. load a project
2.2. disconnect from internet
2.3. hit refresh on browser
2.4. verify that it still loads

**Comment by weagale** [comment]
@ericpyle @deafjava Please review my testing steps and let me know if they are adequate to pass this to Done....

Testing Steps:
1. Uninstalled version 1.0.3 from the Control Panel (Eric and I had installed that for the demo video).
2. Downloaded and installed  [](https://github.com/ubsicap/sltt-app/releases/download/v1.0.15/sltt-app-Setup-1.0.15.exe) 
3. Clicked the sltt-app icon to launch > logged in/authenticated.
4. Resixed the browser to see the version number.
5. Verified  version 2.44.1 is on the parentheses after "Sign Language Translation Tool".
6. Did not wait long enough for update to happen, but Clicked "Sign Out
"UNEXPECTEDLY, errors began to happen and at first the desktop icon would not work immediately.
7. Waited about 30 seconds and the icon restored and launched SLTT again.
8. Resized the browser to see the version number after "Sign Language Translation Tool".
AS EXPECTED, the app has been updated to verrsion 2.46.4
9. Loaded Project "TESTnm"
10. Disconnected from the internet
AS EXPECTED, I can still navigate through the PORTIONS.
THERE is no browser (this is a desktop client/app) so I cannot hit "Refresh" on the browser.

**Comment by ericpyle** [comment]
> @ericpyle @deafjava Please review my testing steps and let me know if they are adequate to pass this to Done....
> 10. Disconnected from the internet
>     AS EXPECTED, I can still navigate through the PORTIONS.
>     THERE is no browser (this is a desktop client/app) so I cannot hit "Refresh" on the browser.

Good point: revised steps:

To test offline:
1. load a project
2. close down sltt-app
3. disconnect from internet
4. open sltt-app 
5. verify that it still loads all the way

**Comment by ericpyle** [comment]
@weagale wrote "UNEXPECTEDLY, errors began to happen and at first the desktop icon would not work immediately."

I'm not sure what you mean by "errors began to happen". Maybe a screen/video capture would be helpful.

**Comment by weagale** [comment]
@ericpyle IT seems the errors only happened on the version 2.44.1 and are not repeatable in version 2.46.4.  So I think that's ok.
Do you want me to back up to version 2.44.1 and try to repeat it?

**Comment by ericpyle** [comment]
> Marking Done because it all passes for the later version...

This error should no longer happen after my fix for https://github.com/ubsicap/sltt-app/issues/2

**Comment by ericpyle** [comment]
> Unless @ericpyle objects, I think tests should be conducted always on newer versions

I agree in general, however, the testing steps for this, did involve an older version so she could test the auto-update to new version worked. Fortunately, I think the latest version should not have this issue since we're only launching one version of the compressor. It does remind me however, that users who have a separate version of the compressor may try to run that compressor alongside the sltt-app, in which case we'll encounter this error again.  So, I should probably change the port number for the sltt-app so that it is separate from the old compressor install.

**Comment by ericpyle** [comment]
Created https://github.com/ubsicap/sltt-app/issues/4 to address the conflicting port
