### ISSUE TITLE
feat(sltt-app): make only one instance of app

### ISSUE THREAD

**Issue by ericpyle** [ubsicap/sltt-app#2]

**Comment by weagale** [comment]
SCENARION 1 Passes:
1. Uninstalled version 1.0.3 from the Control Panel (Eric and I had installed that for the demo video).
2. Downloaded and installed 1.0.5
3. Clicked the sltt-app icon to launch > logged in/authenticated.
4. Minimized the client.
5. Clicked on the sltt icon in the taskbar.
6. Verified sltt restored.
7. Minimized the client.
8. Double-Clicked on the sltt icon icon on the desktop.
9. Verified sltt restored.
