### ISSUE TITLE
chore(sltt-app): experiment with FAT32 and NTFS

### ISSUE THREAD

**Issue by ericpyle** [ubsicap/sltt-app#26]
See also https://signlanguaget-nfl9249.slack.com/archives/C07CDCDMW9K/p1722600499967609

Even though the device says it only supports FAT32 or NTFS, it shows a microSD card as exFAT.
 See https://docs.gl-inet.com/router/en/4/interface_guide/network_storage/#introduction
> The supported disk formats are NTFS, FAT32.

Determine how NTFS compares with FAT32 with respect to how many empty files can be stored in it.
Steps:
1) Format a USB thumbdrive with FAT32
2) Write/run a script that can fill up the drive with empty files under a `emptyFiles` directory
3) Record how many files got written
4) Repeat with NTFS
5) Repeat with exFAT

Summarize results.

NOTE: our current NAS device has a MicroSD card with a capacity of 128GB (Lexar MicroSD XC 1, V30, 3 A1)

Also determine the requirement for max video size (FAT32 only supports up to 4Gb files)

**Comment by EllisBenus** [comment]
Some good information:

Use **FAT32** if you need compatibility and are working with smaller files and volumes.
Use **exFAT** for external drives and larger files, especially if you need cross-platform compatibility.
Use **NTFS** for internal drives, where data integrity, advanced features, and handling a wide range of file sizes are more critical than raw write speed.

**FAT32 and exFAT** both have **"Size on Disk"** which uses much more space for small/empty files. With 20,000 empty files, the size on disk for both formats was 312 megabytes.

**NTFS** doesn't appear to use this method, so storing 20,000 empty files only took up the 58.5 kilobytes of space the files actually occupied.

![image](https://github.com/user-attachments/assets/5c04ff1a-11fa-40be-823f-35c23c1d1099)
![image](https://github.com/user-attachments/assets/622e1933-9050-4452-accc-7489c4e8d5bb)
![image](https://github.com/user-attachments/assets/bb85aea7-1e28-44fd-882e-29f0f09d8b8d)

**Comment by Nathan22Miles** [comment]
I am very skeptical that storing 1000+ files in any directory is a good idea no matter what file system we use.
We are far off the beaten path if we try that and should expect problems.

**Comment by ericpyle** [comment]
> I am very skeptical that storing 1000+ files in any directory is a good idea no matter what file system we use. We are far off the beaten path if we try that and should expect problems.

Well, I was once delusional but experimenting with this did convince me that this is not practical for sharing docs.
