### ISSUE TITLE
feat(sltt-app): add multiple private window support

### ISSUE THREAD

**Issue by ericpyle** [ubsicap/sltt-app#35]
This is needed to make it easier to test multiple clients interacting with the same shared storage.

My idea is to have a special startup mode: when the user holds down Control+SHIFT while starting sltt-app it will prompt them to add a new private window that they can name with a unique name/purpose. The next time they control+shift start it will ask them to select existing ones or create a new (named) private window. 

Each private window will have its own browser cache (partition).

A full feature probably requires upgrading the compressor to work with multiple clients at the same time (and thus separate temp directory folders).

**Comment by weagale** [comment]
1. In a new browser, goto: https://dev.sltt-bible.net/#/
2. Highlight the URL and drag it to your "Bookmarks bar" 
3. Right clickk on the new bookmark > Click "Edit" > Change the name to "SLTT" > Click "Save"
4. Open a new tab > CONFIRM you see the SLTT shortcut.
5. Hold down "CTRL+SHIFT" and click the SLTT shortcut.
Unexpectedly, you are not prompted to add a new private window

**Comment by ericpyle** [comment]
> 1. In a new browser, goto: https://dev.sltt-bible.net/#/
> 2. Highlight the URL and drag it to your "Bookmarks bar"
> 3. Right click on the new bookmark > Click "Edit" > Change the name to "SLTT" > Click "Save"
> 4. Open a new tab > CONFIRM you see the SLTT shortcut.
> 5. Hold down "CTRL+SHIFT" and click the SLTT shortcut.
>    Unexpectedly, you are not prompted to add a new private window

Please note the context is `sltt-app` which is the installed version, not dev.sltt-bible.net :)

**Comment by weagale** [comment]
1. Download and Install [sltt-app-Setup-206004.3.1.exe](https://github.com/ubsicap/sltt-app/releases/download/untagged-ae120709c65224de98c1/sltt-app-Setup-206004.3.1.exe).
2. Hold down "CTRL+SHIFT" and click the SLTT desktop shortcut.
3. Enter your email when prompted > Next
4. Enter your password > Next
5. Observe a message "Hi Craig and Wendy Langley, sltt-app is requesting access to your sltt tenant."
6. Click Ⓧ .
7. CONFIRM that you  see a login button. and can enter the same or a different email and password.
8. Click Login.
9. CONFIRM that you again observe a message "Hi Craig and Wendy Langley, sltt-app is requesting access to your sltt tenant."
10. Click the Checkmark in the circle
11. Confirm that you get a message as follows:
     craigwendy2020@gmail.com: You are not currently a member of any project.
 
     1) Click the logout button to login again with a different email. 
     2) Or ask your project administrator to go to the Settings / Members tab and add: (craigwendy2020@gmail.com)
12. Click the logout button
13. Try to sign in with your usual email/password > Click "Log In"
Unexpectedly, the login dialog says "Wrong email or password"  
14. Sign in elsewhere to CONFIRM you are using the correctemail/ password.
Unfortuneately, it won't let you go back to your original login.  It seems to have remembered the 2nd email.

**Comment by AllisonPyle** [comment]
The scenarios in the PR seemed to work for me. I did make a couple of notes on the general sign-in process [in Slack](https://signlanguaget-nfl9249.slack.com/archives/C057S17G2L9/p1729092903759339).

In general, using a Google login is a little harder in the app than in the browser:

1) I can't use my password manager, and there's no association with my browser history/settings, so I have to type my email address manually the first time and type my password manually (not sure how often I'll need to enter my password).

2) I can't change to a different Google account once I have logged into one in the app UNLESS I first use the new Alt+W command to open a new window and log in as a different user. Are we planning to make this feature more accessible to users? Maybe an icon or something?? Or would an admin do this once to set up a second user on the computer, and then their account would show up as an option for future app logins?

**Comment by ericpyle** [comment]
> 1. I can't use my password manager, and there's no association with my browser history/settings, so I have to type my email address manually the first time and type my password manually (not sure how often I'll need to enter my password).

Users can copy and paste from their password manager, right?

> I can't change to a different Google account once I have logged into one in the app 

Currently the only user-supported way to do this is to have them uninstall and reinstall the app. If @deafjava would like us in general to provide multiple windows for users via menu, he needs to think about the best UI for this.

FWIW, I have this issue in To Prioritize, that MIGHT allow auth0 to always force google to prompt to select the google account to use to sign in https://github.com/ubsicap/sltt/issues/958
