### ISSUE TITLE
fix: Auth0 login screen should load when token expires without a server error

### ISSUE THREAD

**Issue by AllisonPyle** [ubsicap/sltt-app#5]
[EDIT: The way to reproduce this issue (other than waiting to expire) is just to click on the Logout button.]

Actual: When the sltt-app token expires after an idle period, it does not successfully take me to the login screen. Instead, I see the following screen:
![image](https://github.com/ubsicap/sltt-app/assets/145381594/f133fa65-ae42-4b84-abd8-56e865f8f4b3)

When I clicked on "Show technical details," it showed me this:
![image](https://github.com/ubsicap/sltt-app/assets/145381594/fadce2a7-71bb-4677-a5f0-fdb4cc39dbe6)

Expected: When time expires, Auth0 login screen should load to allow me to log back in.

**Comment by ericpyle** [comment]
The issue is that we call `Auth0.logout({ returnTo: window.location.origin })`, and in the context of sltt-app: 

```console
> window.location.origin
'file://'
```

**Comment by weagale** [comment]
Passes Testing by the following steps from Vercel:

Scenario 1: Logout Button

1. Launch sltt-app version greater than 204801.0.20
2. Login to the app (if not already)
3. Click on the Logout button
4. Auth0 should redirect to the login form without an error

**Comment by weagale** [comment]
Passes Testing by the following steps from electron app:

Scenario 2: Expiration

1. Go to https://github.com/ubsicap/sltt-app/releases and download latest release
2. Launch sltt-app version greater than 204801.0.20 (such as [v205001.0.20](https://github.com/ubsicap/sltt-app/tree/v205001.0.20))
3. Login to the app  
4. Wait a minute until your session expires
5. Confirm Auth0 redirects to the login form without an error
